spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:munbanggu;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  profiles:
    include: oauth