spring:
  profiles:
    include:
    - secret
    - oauth
    - s3
  servlet:
    multipart:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:munbanggu;NON_KEYWORDS=USER;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: smtp.naver.com
    port: 465
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
            trust: smtp.naver.com

  redis:
    host: 127.0.0.1 # 3.84.216.196   #[AWS EC2 엔드포인트로 변경]
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  kakao:
    api:
      baseUrl: https://kapi.kakao.com/v1/payment/ready
      adminKey: 53937b88b5a19ee69356275a66741044


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

